---
- name: Configure common things
  hosts: all
  user: ec2-user
  become: True
  roles:
    - roles/common

# - name: Configure master node
#   hosts: master
#   user: root
#   roles:
#     - roles/master
